name: CI

on:
  push: {}
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Check dependencies
      run: |
        go mod tidy
        go fmt ./...
        
        if ! test -z "$(git status -s)"; then
          echo "Git state is dirty"
          git status
          exit 1
        fi

    - name: Build
      run: |
        go vet ./...
        go build -o graphql-transform .

    - name: Test
      run: go test -v -race ./...
